Ticketz/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using NuGet.Protocol.Core.Types;
using Ticketz.Repository.Services;
using Ticketz.ViewModel;

namespace Ticketz.Controllers;

public class ActorsController : Controller
{
    private readonly IActorRepository _actorRepository;
    private readonly IToastNotification _toastNotification;
    public ActorsController(IActorRepository actorRepository, IToastNotification toastNotification)
    {
        _actorRepository = actorRepository;
        _toastNotification = toastNotification;
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        var actors = await _actorRepository.GetAllAsync();
        return View(actors);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create(AddNewActorViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        await _actorRepository.AddActorAsync(model);
        _toastNotification.AddSuccessToastMessage("Actor Created Successfully");
        return RedirectToAction(nameof(Index));
        
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(int id)
    {
        var actor = await _actorRepository.GetByIdAsync(id);
        var actorviewmodel = new UpdateActorViewModel()
        {
            Name=actor.Name,
            Bio = actor.Bio,
            PictureCurrent=actor.Picture,
            
        };
        return View(actorviewmodel);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(UpdateActorViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        await _actorRepository.UpdateActorAsync(model);
        _toastNotification.AddSuccessToastMessage("Actor Updated Successfully");
        return RedirectToAction(nameof(Index));

    }
    public async Task<IActionResult> Details(int id)
    {
        var actor = await _actorRepository.GetByIdAsync(id);
        return View(actor);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        await _actorRepository.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }

}

Ticketz/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Ticketz.Repository.Services;
using Ticketz.ViewModel;

namespace Ticketz.Controllers;

public class CinemasController : Controller
{
    private readonly ICinemaRepository _cinemaRepository;
    private readonly IToastNotification _toastNotification;
    public CinemasController(ICinemaRepository cinemaRepository, IToastNotification toastNotification)
    {
        _cinemaRepository = cinemaRepository;
        _toastNotification = toastNotification;
    }
    [Authorize(Roles = "Admin")]

    public async Task<IActionResult> Index()
    {
        var listOfCinemas = await _cinemaRepository.GetAllAsync();
        return View(listOfCinemas);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create(AddCinemaViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        await _cinemaRepository.AddNewCinemaAsync(model);
        _toastNotification.AddSuccessToastMessage("Cinema Created Successfully");
        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(int id)
    {
        var cinema = await _cinemaRepository.GetByIdAsync(id);
        var cimaVM = new UpdateCinemaViewModel()
        {
            Id = cinema.Id,
            Name = cinema.Name,
            Description = cinema.Description,
            LogoCurrent = cinema.Logo
        };
        return View(cimaVM);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(UpdateCinemaViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        await _cinemaRepository.UpdateCinemaAsync(model);
        _toastNotification.AddSuccessToastMessage("Cinema Updated Successfully");
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Details(int id)
    {
        var cinema = await _cinemaRepository.GetByIdAsync(id);
        return View(cinema);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        await _cinemaRepository.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

Ticketz/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using Ticketz.Repository.Services;
using Ticketz.ViewModel;

namespace Ticketz.Controllers;
public class MoviesController : Controller
{
    private readonly IMovieRepository _movieRepository;
    private readonly IToastNotification _toast;
    public MoviesController(IMovieRepository movieRepository, IToastNotification toast)
    {
        _movieRepository = movieRepository;
        _toast = toast;
    }
    public async Task<IActionResult> Index()
    {
        var movies = await _movieRepository.GetAllAsync();
        return View(movies);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create()
    {
        var list = await _movieRepository.MovieDropDawnListAsync();
        ViewBag.Nationalities = new SelectList(list.NationalityList, "Id", "Name");
        ViewBag.Actors = new SelectList(list.ActorList, "Id", "Name");
        ViewBag.Cinemas = new SelectList(list.CinemaList, "Id", "Name");
        ViewBag.Producers = new SelectList(list.ProducerList, "Id", "Name");
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create(CreateMovieViewModel model)
    {
        if (!ModelState.IsValid && model.NationalityId == 0 && model.CinemaId == 0 &&
            model.Genre == 0 && model.ProducerId == 0) 
        {
            var list = await _movieRepository.MovieDropDawnListAsync();
            ViewBag.Nationalities = new SelectList(list.NationalityList, "Id", "Name");
            ViewBag.Actors = new SelectList(list.ActorList, "Id", "Name");
            ViewBag.Cinemas = new SelectList(list.CinemaList, "Id", "Name");
            ViewBag.Producers = new SelectList(list.ProducerList, "Id", "Name");
            return View(model);
        }
        await _movieRepository.AddNewMovieAsync(model);
        _toast.AddSuccessToastMessage("Movie Created Successfully");
        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(int id)
    {

        var list = await _movieRepository.MovieDropDawnListAsync();
        ViewBag.Nationalities = new SelectList(list.NationalityList, "Id", "Name");
        ViewBag.Actors = new SelectList(list.ActorList, "Id", "Name");
        ViewBag.Cinemas = new SelectList(list.CinemaList, "Id", "Name");
        ViewBag.Producers = new SelectList(list.ProducerList, "Id", "Name");

        var movieVM = await _movieRepository.GetByIdAsync(id);
        var movie = new UpdateMovieViewModel()
        {
            Title=movieVM.Title,
            Description = movieVM.Description,
            Price = movieVM.Price,
            PictureCurrent = movieVM.Picture,
            StartDate=movieVM.StartDate,
            EndDate=movieVM.EndDate,
            Genre=movieVM.Genre,
            Actor_Movie=movieVM.Actor_Movie.Select(e=>e.ActorId).ToList(),
            CinemaId = movieVM.CinemaId,
            ProducerId=movieVM.ProducerId,
            NationalityId=movieVM.NationalityId,
        };

        return View(movie);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(UpdateMovieViewModel model)
    {
        if (!ModelState.IsValid && model.NationalityId == 0 && model.CinemaId == 0 &&
            model.Genre == 0 && model.ProducerId == 0)
        {
            var list = await _movieRepository.MovieDropDawnListAsync();
            ViewBag.Nationalities = new SelectList(list.NationalityList, "Id", "Name");
            ViewBag.Actors = new SelectList(list.ActorList, "Id", "Name");
            ViewBag.Cinemas = new SelectList(list.CinemaList, "Id", "Name");
            ViewBag.Producers = new SelectList(list.ProducerList, "Id", "Name");
            return View(model);
        }
        await _movieRepository.UpdateNewMovieAsync(model);
        _toast.AddSuccessToastMessage("Movie Updated Successfully");
        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "User")]
    public async Task<IActionResult> Details(int id)
    {
        var movie = await _movieRepository.GetByIdAsync(id);
        return View(movie);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        await _movieRepository.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Search(string title)
    {
        var moviesList = await _movieRepository.GetAllAsync();

        if (!string.IsNullOrEmpty(title))
        {
            var filteredResult = await _movieRepository.FindAsync(n => n.Title.ToLower().Contains(title.ToLower()) || n.Description.ToLower().Contains(title.ToLower()));
            return View("Index", filteredResult);
        }

        return View("Index", moviesList);
    }
}

Ticketz/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Ticketz.Cart;
using Ticketz.Repository.Services;
using Ticketz.ViewModel;

namespace Ticketz.Controllers;
public class OrdersController : Controller
{
    private readonly IOrderRepository _orderRepository;
    private readonly ShoppingCart _cart;
    private readonly IMovieRepository _movieRepository;
    public OrdersController(IOrderRepository orderRepository,
        ShoppingCart cart, IMovieRepository movieRepository)
    {
        _orderRepository = orderRepository;
        _cart = cart;
        _movieRepository = movieRepository;
    }

    public async Task<IActionResult> Index()
    {
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        string roleUser = User.FindFirstValue(ClaimTypes.Role);

        var order = await _orderRepository.GetOrdersByUserIdRoleAsync(userId, roleUser);
        return View(order);
    }
    public IActionResult ShoppingCart()
    {
        var items = _cart.GetShoppingCartItems();
        _cart.ShoppingCartItems = items;

        var response = new ShoppingCartViewModel()
        {
            ShoppingCart = _cart,
            ShoppingCartTotal = _cart.TotalPriceOrder()
        };

        return View(response);
    }
    [Authorize(Roles ="User")]
    public async Task<IActionResult> AddItemToCart(int id)
    {
        var item = await _movieRepository.GetByIdAsync(id);

        if (item != null)
        {
            _cart.AddItemToCart(item);
        }
        return RedirectToAction(nameof(ShoppingCart));
    }

    public async Task<IActionResult> RemoveItemFromCart(int id)
    {
        var item = await _movieRepository.GetByIdAsync(id);

        if (item != null)
        {
            _cart.RemoveItemFromCart(item);
        }
        return RedirectToAction(nameof(ShoppingCart));
    }

    public async Task<IActionResult> CompleteOrder()
    {
        var items = _cart.GetShoppingCartItems();
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

        await _orderRepository.AddOrderAsync(items, userId, userEmailAddress);
        await _cart.ClearShoppingCartAsync();

        return View();
    }
}

Ticketz/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Ticketz.Repository.Services;
using Ticketz.ViewModel;

namespace Ticketz.Controllers;

public class ProducersController : Controller
{
    private readonly IProducerRepository _producerRepository;
    public ProducersController(IProducerRepository producerRepository)
    {
        _producerRepository = producerRepository;
    }
    [Authorize(Roles = "Admin")]

    public async Task<IActionResult> Index()
    {
        var producer = await _producerRepository.GetAllAsync();
        return View(producer);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create()
    {
        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Create(AddNewProducerViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        await _producerRepository.AddProducerAsync(model);
        return RedirectToAction(nameof(Index));

    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(int id)
    {
        var producer = await _producerRepository.GetByIdAsync(id);
        var producerVM = new UpdateProducerViewModel()
        {
            Name=producer.Name,
            Bio=producer.Bio,
            PictureCurrent=producer.Picture,
        };
        return View(producerVM);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Update(UpdateProducerViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        await _producerRepository.UpdateProducerAsync(model);
        return RedirectToAction(nameof(Index));

    }
    public async Task<IActionResult> Details(int id)
    {
        var producer = await _producerRepository.GetByIdAsync(id);
        return View(producer);
    }
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Delete(int id)
    {
        await _producerRepository.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

Ticketz/Views/Movies/Create.cshtml
@model CreateMovieViewModel

@{
    ViewData["Title"] = "Create Movie";
}
<h3 class="ipc"><i class="bi bi-file-earmark-plus"></i> Create Movie </h3>
<hr />

<section class="row justify-content-between">
    <div class="col-md-5 ">
        <form asp-action="Create" asp-controller="Movies" enctype="multipart/form-data" method="post" >
    
             <div class="form-group">
                <label class="text-muted" asp-for="Title"></label>
                <input type="text" class="form-control" asp-for="Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Description" class="text-muted"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group w-50">
                <label asp-for="Price" class="text-muted"></label>
                <input type="number" asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="custom-file mt-3" id="ww">
                <input type="file" class="custom-file-input" asp-for="Picture" accept="image/*" />
                <label class="custom-file-label" asp-for="Picture"></label>
                <div><small id="emailHelp" class="form-text text-muted">Only .jpg, .png, .png files are allowed</small></div>
                <span asp-validation-for="Picture" class="text-danger d_block"></span>
            </div>
            <div class="form-group ">
                <label asp-for="StartDate" class="text-muted"></label>
                <input type="date" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group ">
                <label asp-for="EndDate" class="text-muted"></label>
                <input type="date" asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="text-muted" asp-for="NationalityId"></label>
                <select class="form-control" asp-for="NationalityId" asp-items=" ViewBag.Nationalities">
                    <option value="">--Select Nationality--</option>
                </select>
                <span asp-validation-for="NationalityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="text-muted" asp-for="CinemaId"></label>
                <select class="form-control" asp-for="CinemaId" asp-items="ViewBag.Cinemas">
                    <option value="">--Select Cinema--</option>
                </select>
                <span asp-validation-for="CinemaId" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label class="text-muted" asp-for="ProducerId"></label>
                <select class="form-control" asp-for="ProducerId" asp-items="ViewBag.Producers">
                    <option value="">--Select Producer--</option>
                </select>
                <span asp-validation-for="ProducerId" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label class="text-muted" asp-for="Genre"></label>
                <select class="form-control" asp-for="Genre" asp-items="Html.GetEnumSelectList<Genre>()">
                   <option value="">--Select Genre--</option>
                   </select>
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label class="text-muted" asp-for="Actor_Movie"></label>
                <select class="form-control" asp-for="Actor_Movie" asp-items="ViewBag.Actors" multiple>
                </select>
                <span asp-validation-for="Actor_Movie" class="text-danger"></span>
            </div> 
            <br />
            <button type="submit" class="btn btn-success">
                <i class="bi bi-floppy"></i> Create
            </button>
            @* <input type="submit" class="btn btn-success" value="Create" /> *@
            @* <a asp-action="Create" asp-controller="Movies" class="btn btn-success"><i class="bi bi-plus"></i> Create</a> *@
            <a asp-action="Index" asp-controller="Movies" class="btn btn-danger"><i class="bi bi-x-circle"></i> Cancel</a>
        </form>
    </div>

<div class="col-md-4">
    <div id="IdPoster">
            <img src="" class="cover-preview  d-none  img-thumbnail" alt="Picture" style="width:370px;height:450px;margin-top:120px;" />
    </div>
</div>
</section>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function() {
            $('#Picture').on('change', function() {
                $('.cover-preview').attr('src', window.URL.createObjectURL(this.files[0])).removeClass('d-none');
            });
        });
    </script>
}

Ticketz/Views/Movies/Details.cshtml
@model Movie
@{
    ViewData["Title"] = Model.Title;
}
<h3 style="margin-left:10px;" class="ipc">Movie Details</h3>
<div class="row mt-5 justify-content-between" style="margin-top:50px;">
    
    <div class="col-md-3">
        <img style="margin-top:10px;" src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Picture))" class="img-thumbnail" alt="Poster" />
    </div>
    <div class="col-md-8">
        <div class="d-flex justify-content-between mb-3">
            <h3>@Model.Title</h3>
        </div>
        <span class="text-muted" style="margin-right:8px;">
            <i class="bi bi-ticket-perforated"></i>
            @Model.Price.ToString("c")
        </span>
        <span class="text-muted " style="margin-left:25px;">
            <i class="bi bi-film"></i>
            @Model.Genre
        </span>
        <br />
        <br />
        <span class="text-muted " >
            <i class="bi bi-globe-americas"></i>
            @Model.Nationality.Name
        </span>
        <br />
        <br />
        <span class="text-muted" style="margin-right:8px;">
            <span class="badge bg-success text-white">Start Date</span> : <i class="bi bi-calendar-date"></i>
            @Model.StartDate.ToString("dd MMMMM yyyy")
        </span>
        <span class="text-muted " style="margin-left:20px;">
            <span class="badge bg-danger text-white">End Date</span> : <i class="bi bi-calendar-date"></i>
            @Model.EndDate.ToString("dd MMMMM yyyy")
        </span>
        <br />
        <br />
        <p class="card-text ">
            <b>Status :  </b>
            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
            {
                <span class="badge bg-success text-white">AVAILABLE</span>
            }
            else if (DateTime.Now > Model.EndDate)
            {
                <span class="badge bg-danger text-white">EXPIRED</span>
            }
            else
            {
                <span class="badge bg-primary text-white">UPCOMING</span>
            }
        </p>

        <h5>Story Line  :  </h5>
        <p class="text-justify mt-3">@Model.Description</p>
       
    </div>
    <div class="row" style="margin-top:65px;">
    <h3 style="margin-left:10px;" class="ipc">Cinema</h3>
        <img style="border-radius:50%;width:191px;height:180px;margin-left:530px;" src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Cinema.Logo))" alt="Poster" />
        <a asp-action="Details" asp-controller="Cinemas" asp-route-id="@Model.Cinema.Id" style="width:280px;height:40px; margin-top:70px;" class="btn btn-outline-secondary"><i class="bi bi-eye-fill"></i> @Model.Cinema.Name </a>
</div>
    <div class="row" style="margin-top:73px;">
        <h3 style="margin-left:10px;" class="ipc">Producer</h3>
        <img style="border-radius:50%;width:191px;height:180px;margin-left:530px;" src="data:image/jpg;base64,@(Convert.ToBase64String(Model.Producer.Picture))" alt="Poster" />
        <a asp-action="Details" asp-controller="Producers" asp-route-id="@Model.Producer.Id" style="width:280px;height:40px; margin-top:70px;" class="btn btn-outline-secondary"><i class="bi bi-eye-fill"></i> @Model.Producer.Name </a>
    </div>
    <div class="row" style="margin-top:73px;">
        <h3 style="margin-left:10px;" class="ipc">Actors</h3>
@foreach(var item in Model.Actor_Movie){
            <img style="border-radius:50%;width:191px;height:180px;margin-left:100px;" src="data:image/jpg;base64,@(Convert.ToBase64String(item.Actor.Picture))" alt="Poster" />
            <a asp-action="Details" asp-controller="Actors" asp-route-id="@item.ActorId" style="width:280px;height:40px; margin-top:70px;" class="btn btn-outline-secondary"><i class="bi bi-eye-fill"></i> @item.Actor.Name </a>
}
    </div>
<a asp-action="Index" style="margin-left:540px;width:250px;" class="btn btn-danger mt-3"><i class="bi bi-x-circle"></i> Back To List</a>

Ticketz/Views/Movies/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Movies";
}

<h3 class="ipc"><i class="bi bi-tv"></i> Movies</h3>
<hr />
 @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")){
<a asp-action="Create" asp-controller="Movies" class="btn btn-primary"><i class="bi bi-file-earmark-plus"></i> Create Movie</a>
<br />
<br />
}
<div class="row ">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3  rowww">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-dark   small-header">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Title
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="data:image/jpg;base64,@(Convert.ToBase64String(item.Picture))"style="width:207px;height:270px;"  alt="@item.Title">
                    </div>
                    <div class="col-md-6  card">
                        <div class="card-body" >
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Genre: </b>@item.Genre</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <div class="card-actions">
                                    <a style="margin-left:10px;" class="btn btn-info   purple-button" asp-action="Update" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                <a href="javascript:;" style="margin-left:123px;" class="js-delete  btn btn-danger   red-button" data-id="@item.Id"><i class="bi bi-trash"></i></a>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Details
                                </a>

                                    <a style="margin-left:37px;" class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                                    asp-controller="Orders"
                                   asp-action="AddItemToCart"
                                   asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
             
        $(document).ready(function() {
            $('.js-delete').on('click', function() {
                var btn = $(this);


                bootbox.confirm({
                    message: 'Are you sure that you need to delete this Movie!',
                    buttons: {
                        confirm: {
                            label: 'Yes',
                            className: 'btn-danger'
                        },
                        cancel: {
                            label: 'No',
                            className: 'btn-outline-secondary'
                        }
                    },
                    callback: function(result) {
                        if (result) {
                        $.ajax({
                                url: '/Movies/Delete/' + btn.data('id'),
                                success: function() {
                                    var moviecontainer = btn.parents('.rowww');

                                    moviecontainer.addClass('animate__animated animate__bounceOut');
                                    setTimeout(function() {
                                        moviecontainer.remove();
                                    }, 1000);
                                    toastr.warning('Movie is remove successful!');
                                },
                                error: function() {
                                    toastr.error('---error!!---');
                                }
                            });
                        }

                    }
                });


            });
        });
    </script>
}